#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-semilla-gui
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2012 Carlos adrian Espinoza Fermin <carlosarmikhael@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-semilla-gui"

case ${1} in

	remove|upgrade|deconfigure)

        # Aquí va lo que el paquete debe configurar/crear/borrar antes de
        # removerse. Lenguaje a usar: BASH.

	;;

	failed-upgrade)

        # Aquí va lo que el paquete debe configurar/crear/borrar si la
        # desinstalación falla. Lenguaje a usar: BASH.

	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
